name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your actual requirements file

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Build
      run: |
        # Add any build steps here, e.g., compiling, packaging, etc.

    - name: Run app.py
      run:  python app.py
        cd path/to/your/app  # Change to the directory where app.py is located
      
